reglist = {"REG_B", "REG_C", "REG_D", "REG_E", "REG_H", "REG_L", "AT(REG_HL)", "REG_A"}

function printf(x,...) print(x:format(...)) end

printf("//generated by %s", arg[0])
for i=1,#reglist,1 do
	for j=1,#reglist,1 do
		if j == 7 and i == 7 then
			printf("op(0x76, 4, HALT);")
			goto cont
		end
		local c = 4
		if i == 7 or j == 7 then
			c = 8
		end
		printf("op(0x%.2X, %i, LD, %s, %s);", 0x40+((i-1)*#reglist+j-1), c, reglist[i], reglist[j])
		::cont::
	end
end
