instrs = {"ADD_8, REG_A", "ADC, REG_A", "SUB", "SBC, REG_A", "AND", "XOR", "OR", "CP"}
regs = {"REG_B", "REG_C", "REG_D", "REG_E", "REG_H", "REG_L", "AT(REG_HL)", "REG_A"}

function printf(x,...) print(x:format(...)) end

printf("//generated by %s", arg[0])
for i,instr in ipairs(instrs) do
	for j,reg in ipairs(regs) do
		local c = 4
		if j == 7 then
			c = 8
		end
		printf("op(0x%.2X, %i, %s, %s);", 0x80+((i-1)*#regs+j-1), c, instr, reg)
	end
end
